# Generated by Django 4.2.7 on 2023-11-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "student_messenger",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "student_phonenumber",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("parent_name", models.CharField(max_length=50)),
                ("parent_messenger", models.CharField(max_length=50)),
                ("parent_phonenumber", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "студент",
                "verbose_name_plural": "студенты",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_days",
                    models.CharField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        max_length=1,
                    ),
                ),
                ("time", models.TimeField()),
                ("lessons_left", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "расписание",
                "verbose_name_plural": "расписания",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("done", models.BooleanField(default=False)),
                ("video", models.CharField(blank=True, max_length=100, null=True)),
                ("report", models.CharField(blank=True, max_length=300, null=True)),
                ("homework", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "занятие",
                "verbose_name_plural": "занятия",
            },
        ),
    ]
