# Generated by Django 4.2.7 on 2023-11-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_schedule_options_alter_lesson_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="week_days",
            field=models.CharField(
                choices=[
                    ("MON", "Понедельник"),
                    ("TUE", "Вторник"),
                    ("WED", "Среда"),
                    ("THU", "Четверг"),
                    ("FRI", "Пятница"),
                    ("SAT", "Суббота"),
                    ("SUN", "Воскресенье"),
                ],
                max_length=20,
                verbose_name="День недели",
            ),
        ),
    ]
