# Generated by Django 4.2.7 on 2023-11-29 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_alter_schedule_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="students.schedule",
            ),
        ),
    ]
