# Generated by Django 4.2.7 on 2023-11-30 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mentors", "0001_initial"),
        ("students", "0007_lesson_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="mentor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="mentors.mentor",
            ),
            preserve_default=False,
        ),
    ]
