# Generated by Django 4.2.7 on 2023-11-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "phonenumber",
                    models.CharField(
                        max_length=50, verbose_name="Номер телефона наставника"
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Telegram ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "ментор",
                "verbose_name_plural": "менторы",
            },
        ),
    ]
